# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_data', '0010_auto_20160212_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='senator',
            name='start',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
