# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_data', '0011_senator_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senator',
            name='rank',
        ),
        migrations.AddField(
            model_name='senator',
            name='end',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
