# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_data', '0013_bill_congress'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosponsorship',
            name='congress',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
